### PR TITLE
Preparing site for v1 launch

### PR DESCRIPTION
**Pull request by arrowtype**
[work in progress]

See deploy preview at https://deploy-preview-67--determined-heisenberg-38577d.netlify.com/, and click the "Get Recursive" button to see this tool.

For more background on design & future goals, see https://github.com/arrowtype/recursive-minisite/issues/33

Next steps for an "MVP" implementation:

- [x] make drawer show/hide even with purged CSS
- [x] fix style overrides that are causing incorrect sans style in hero
- [x] fix formatting on embed code
- [x] make sidebar scroll if page is too short
- [x] update for slnt/CRSV axes
- [x] ask Rod to add new version of recursive to sandbox
- [x] make header for sidebar w/ "From Google Fonts" and "Download" options
- [x] setup "download" link (to github releases)
- [x] make better spacing on range/pinned option
- [x] make it possible to exit sidebar with `esc`
- [x] make it possible to exit sidebar by clicking outside of it
- [x] fix uneven background color change (comment below)
- [x] add listener to adjust height on iOS on page height change
- [x] prevent scrolling behind sidebar between browsers
  - [x] prevent unintentional smooth scrolling on chrome

**Next**

Temporarily moving UI update work to https://github.com/arrowtype/gf-url-api-configurator/pull/2. Will integrate back here soon.

**Later**
- [x] make info panels open to left rather than off the page (are these even needed?)
- [x] update slider styles to match main page
- [x] update style toolbar in main page to match nav height so button sits better
- [x] plan out how preview can be shown in next version/update

### CODE REVIEW

**Comment by arrowtype** [comment]
background changing strangely, almost like _two_ backgrounds are affected:

image

**Comment by arrowtype** [comment]
This scrolls poorly on iOS Safari, so it may have to become a standalone page – either on mobile or just in general.

**Comment by arrowtype** [comment]
Dave's feedback:
- axes should be "turned on" / requested (my thought: but should they be opt-out?)
- can axes be turned on?
- "pinned" ranges must allow middle values because the API allows that to be requested
- "pinning" should allow a "pill on a track" view, rather than the slider

Will check to verify:
- [ ] does requesting a middle value call the full axis, or will the API respond with a instanced version?

**Comment by arrowtype** [comment]
Per Dave's feedback, I'll update ranges and "pinned" sliders to look more like this:

image

**Comment by arrowtype** [comment]
- [ ] let “pinned” sliders have intermediate values (at least `0.5` or `0.25` steps for MONO & CASL)
- [ ] Make button more obvious – maybe even trigger it automatically at end of page, or at least make it wiggle periodically 
- [ ] double-check that analytics are working well
- [ ] Add section at bottom of main page “Get it on Google Fonts” (probably before character grid)
- [ ] Add link to PDF specimen
- [ ] update styling to be more obvious of selected ranges
- [ ] start with default instance pinned, then allow users to opt into ranges

**Comment by RoelN** [comment]
@arrowtype Images can be optimised (SVG with `svgo`, PNG with `ImageOptim`, for instance)

**Comment by arrowtype** [comment]
Thanks, @RoelN! Yeah, I have been using imageOptim (it's awesome), but I think to get serious gains I need to generate different image sizes with imagemagick, then use srcset. Do you know if there is a quicker way to do this than just writing a shell script for it?

**Pull request merged**
